version: '3.3'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./.data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=TNTSucks!
      - POSTGRES_DB=db
    ports:
      - 2137:5432
